arb-dir: lib/src/presentation/localization/arb_file
template-arb-file: en.arb
output-localization-file: app_localizations.dart
synthetic-package: false
output-dir: lib/src/presentation/localization
use-escaping: true
nullable-getter: false
